import NavBar from './components/navbar/NavBar'
import './globals.css'
import type { Metadata } from 'next'
import { Capriola } from "next/font/google";

const capriola = Capriola({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-capriola",
});
export const metadata: Metadata = {
  title: 'Safvan | Software Developer',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html
      lang="en"
      className={`${capriola.variable} `}
    >
      <body>
        <NavBar />
        <main>
          {children}
        </main>
      </body>
    </html>
  )
}
