import NavBar from './components/navbar/NavBar'
import './globals.css'
import type { Metadata } from 'next'


export const metadata: Metadata = {
  title: 'Safvan | Software Developer',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <NavBar/>
        <main>
          {children}
        </main>
      </body>
    </html>
  )
}
